train_test_validation: true
data_integrity: true
model_evaluation: true
max_samples: 1000
random_state: 42
save_results: true
output_dir: /home/fadelco/workspace/deepsight/deepchecks_results
save_display: true
parse_results: true
batch_size: 8
