config: 'num_classes=101 label_to_class_map={0: ''apple_pie'', 1: ''baby_back_ribs'',
  2: ''baklava'', 3: ''beef_carpaccio'', 4: ''beef_tartare'', 5: ''beet_salad'', 6:
  ''beignets'', 7: ''bibimbap'', 8: ''bread_pudding'', 9: ''breakfast_burrito'', 10:
  ''bruschetta'', 11: ''caesar_sa'
num_classes: '101'
label_to_class_map/0: apple_pie
label_to_class_map/1: baby_back_ribs
label_to_class_map/2: baklava
label_to_class_map/3: beef_carpaccio
label_to_class_map/4: beef_tartare
label_to_class_map/5: beet_salad
label_to_class_map/6: beignets
label_to_class_map/7: bibimbap
label_to_class_map/8: bread_pudding
label_to_class_map/9: breakfast_burrito
label_to_class_map/10: bruschetta
label_to_class_map/11: caesar_salad
label_to_class_map/12: cannoli
label_to_class_map/13: caprese_salad
label_to_class_map/14: carrot_cake
label_to_class_map/15: ceviche
label_to_class_map/16: cheesecake
label_to_class_map/17: cheese_plate
label_to_class_map/18: chicken_curry
label_to_class_map/19: chicken_quesadilla
label_to_class_map/20: chicken_wings
label_to_class_map/21: chocolate_cake
label_to_class_map/22: chocolate_mousse
label_to_class_map/23: churros
label_to_class_map/24: clam_chowder
label_to_class_map/25: club_sandwich
label_to_class_map/26: crab_cakes
label_to_class_map/27: creme_brulee
label_to_class_map/28: croque_madame
label_to_class_map/29: cup_cakes
label_to_class_map/30: deviled_eggs
label_to_class_map/31: donuts
label_to_class_map/32: dumplings
label_to_class_map/33: edamame
label_to_class_map/34: eggs_benedict
label_to_class_map/35: escargots
label_to_class_map/36: falafel
label_to_class_map/37: filet_mignon
label_to_class_map/38: fish_and_chips
label_to_class_map/39: foie_gras
label_to_class_map/40: french_fries
label_to_class_map/41: french_onion_soup
label_to_class_map/42: french_toast
label_to_class_map/43: fried_calamari
label_to_class_map/44: fried_rice
label_to_class_map/45: frozen_yogurt
label_to_class_map/46: garlic_bread
label_to_class_map/47: gnocchi
label_to_class_map/48: greek_salad
label_to_class_map/49: grilled_cheese_sandwich
label_to_class_map/50: grilled_salmon
label_to_class_map/51: guacamole
label_to_class_map/52: gyoza
label_to_class_map/53: hamburger
label_to_class_map/54: hot_and_sour_soup
label_to_class_map/55: hot_dog
label_to_class_map/56: huevos_rancheros
label_to_class_map/57: hummus
label_to_class_map/58: ice_cream
label_to_class_map/59: lasagna
label_to_class_map/60: lobster_bisque
label_to_class_map/61: lobster_roll_sandwich
label_to_class_map/62: macaroni_and_cheese
label_to_class_map/63: macarons
label_to_class_map/64: miso_soup
label_to_class_map/65: mussels
label_to_class_map/66: nachos
label_to_class_map/67: omelette
label_to_class_map/68: onion_rings
label_to_class_map/69: oysters
label_to_class_map/70: pad_thai
label_to_class_map/71: paella
label_to_class_map/72: pancakes
label_to_class_map/73: panna_cotta
label_to_class_map/74: peking_duck
label_to_class_map/75: pho
label_to_class_map/76: pizza
label_to_class_map/77: pork_chop
label_to_class_map/78: poutine
label_to_class_map/79: prime_rib
label_to_class_map/80: pulled_pork_sandwich
label_to_class_map/81: ramen
label_to_class_map/82: ravioli
label_to_class_map/83: red_velvet_cake
label_to_class_map/84: risotto
label_to_class_map/85: samosa
label_to_class_map/86: sashimi
label_to_class_map/87: scallops
label_to_class_map/88: seaweed_salad
label_to_class_map/89: shrimp_and_grits
label_to_class_map/90: spaghetti_bolognese
label_to_class_map/91: spaghetti_carbonara
label_to_class_map/92: spring_rolls
label_to_class_map/93: steak
label_to_class_map/94: strawberry_shortcake
label_to_class_map/95: sushi
label_to_class_map/96: tacos
label_to_class_map/97: takoyaki
label_to_class_map/98: tiramisu
label_to_class_map/99: tuna_tartare
label_to_class_map/100: waffles
batch_size: '8'
num_workers: '4'
pin_memory: 'False'
accelerator: auto
precision: bf16-mixed
val_check_interval: '1'
epochs: '5'
label_smoothing: '0.0'
lr: '0.001'
lrf: '0.01'
weight_decay: '0.0005'
reweight_classes: 'False'
monitor: val_f1score
patience: '10'
min_delta: '0.001'
mode: max
experiment_name: foodwaste_classification
run_name: default
log_best_model: 'True'
tracking_uri: http://localhost:5000
dirpath: /home/fadelco/workspace/deepsight/checkpoints
filename: best-{epoch:02d}
save_weights_only: 'True'
